core/urls.py
from django.contrib import admin
from django.conf.urls import include, url, static
from django.urls import path
from . import settings
from mof_network import views


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'', include('mof_network.urls')),
    url(r'accounts/login/$', views.login_view, name='login'),
    url(r'accounts/logout/$', views.logout_view, name='logout'),
]

if settings.DEBUG:
    urlpatterns += static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mof_network/urls.py
from django.conf.urls import url
from django.conf import settings
from . import views
from django.views.generic import RedirectView
from django.conf.urls.static import static

# SET THE NAMESPACE!
app_name = 'mof'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^d3map/$', views.MapView.as_view(), name='map_view'),
    # url(r'^about/$', views.AboutView.as_view(), name='about'),
    url(r'^post/(?P<pk>\d+)/publish/$', views.post_publish, name='post_publish'),
    url(r'^drafts/$', views.DraftListView.as_view(), name='mof_draft_list'),
    url(r'^mof/(?P<pk>[\d\w]+)/comment/$', views.add_comment_to_mof, name='add_comment_to_mof'),
    url(r'^comment/(?P<pk>[\d\w]+)/approve/$', views.comment_approve, name='comment_approve'),
    url(r'^comment/(?P<pk>[\d\w]+)/remove/$', views.comment_remove, name='comment_remove'),
    url(r'^mof/$', views.MofListView.as_view(), name='mof_list'),
    url(r'^mof/(?P<pk>[A-Z\d]+)/$', views.MofDetailView.as_view(), name='mof_detail'),
    url(r'^mof/new/$', views.MofCreateView.as_view(), name='mof_new'),
    url(r'^mof/update/(?P<pk>[A-Z\d]+)/$', views.MofUpdateView.as_view(), name='mof_update'),
    url(r'^mof/delete/(?P<pk>[A-Z\d]+)/$', views.MofDeleteView.as_view(), name='mof_delete'),
    url(r'^mof/approve/(?P<pk>[A-Z\d]+)/$', views.MofDetailView.as_view(), name='mof_approve'),
    url(r'^d3map/ajax/add/', views.ajax_render, name='ajax_add'),
]

mof_network/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse


# Each model is a Python class that subclasses django.db.models.Model
# Each attribute of the model represents a database field.
# With all of this, Django gives you an automatically-generated database-access API.

class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    text = models.TextField()
    date_create = models.DateTimeField(default=timezone.now)
    date_publish = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.date_publish = timezone.now()
        self.save()

    # def approve_comments(self):
    #     return self.comments.filter(approved=True)

    def get_absolute_url(self):
        return reverse('mof:post_detail_view', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title


class Mof(models.Model):
    name = models.CharField(max_length=255, primary_key=True)
    lcd = models.FloatField()
    pld = models.FloatField()
    area = models.FloatField()
    density = models.FloatField()
    formula = models.CharField(max_length=255)
    space_group = models.CharField(max_length=255)
    vol_frac = models.FloatField()
    fingerprint = models.ImageField(upload_to='comm_contrib', blank=True)
    # approved = models.BooleanField(default=False)
    #
    # def approve(self):
    #     self.approved = True
    #     self.save()

    def get_absolute_url(self):
        return reverse('mof:mof_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name


class Connection(models.Model):
    source = models.ForeignKey('mof_network.Mof', related_name='A', on_delete=models.CASCADE)
    target = models.ForeignKey('mof_network.Mof', related_name='B', on_delete=models.CASCADE)

    # def get_absolute_url(self):
    #     return reverse('mof:post_detail_view', kwargs={'pk': self.pk})

    def __str__(self):
        return '{} is correlated with {}'.format(self.source, self.target)


class Comment(models.Model):
    mof = models.ForeignKey('mof_network.Mof', related_name='comments', on_delete=models.CASCADE)
    author = models.CharField(max_length=255)
    text = models.TextField()
    create_date = models.DateTimeField(default=timezone.now)
    publish_date = models.DateTimeField(blank=True, null=True)
    approved = models.BooleanField(default=False)

    def approve(self):
        self.approved = True
        self.save()

    def get_absolute_url(self):
        return reverse('mof:mof_list')

    def __str__(self):
        return self.text

mof_network/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import *


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('author', 'title', 'text')

        widgets = {
            'title': forms.TextInput(attrs={'class': 'textInput'}),
            'text': forms.Textarea(attrs={'class': 'editable medium-editor-textarea postContent'})
        }


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('author', 'text')

        widgets = {
            'author': forms.TextInput(attrs={'class': 'textInput'}),
            'text': forms.Textarea(attrs={'class': 'editable medium-editor-textarea'})
        }


class MofForm(forms.ModelForm):

    class Meta:
        model = Mof
        fields = ('name', 'lcd', 'pld', 'area', 'density', 'formula', 'space_group', 'vol_frac', 'fingerprint')

        widgets = {
            'name': forms.TextInput(attrs={'class': 'textInput'}),
            'lcd': forms.NumberInput(attrs={'class': 'NumberInput'}),
            'pld': forms.NumberInput(attrs={'class': 'NumberInput'}),
            'area': forms.NumberInput(attrs={'class': 'NumberInput'}),
            'density': forms.NumberInput(attrs={'class': 'NumberInput'}),
            'formula': forms.TextInput(attrs={'class': 'textInput'}),
            'space_group': forms.TextInput(attrs={'class': 'textInput'}),
            'vol_frac': forms.NumberInput(attrs={'class': 'textInput'})
        }

mof_network/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import (CreateView, DeleteView, DetailView, ListView, TemplateView, UpdateView)
from .forms import PostForm, CommentForm, MofForm
from .models import *
import json
import base64
import logging
logger = logging.getLogger(__name__)


class IndexView(TemplateView):
    template_name = 'mof_network/index.html'


class AboutView(TemplateView):
    template_name = 'mof_network/about.html'


class MapView(TemplateView):
    context_object_name = 'mofs'
    model = Mof
    template_name = 'mof_network/map_view.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['Node'] = Mof.objects \
            .raw('SELECT name, fingerprint FROM mof_network_mof WHERE name="OWITAQ"')[0]
        print(context)
        return context


@csrf_exempt
def ajax_render(request):
    model = Mof
    name = str(request.POST.get('mof_name'))
    mof = Mof.objects.all().filter(name__exact=name).get()
    print(mof.fingerprint)
    with open(mof.fingerprint.path, 'rb') as image_file:
        encoded_string = base64.b64encode(image_file.read())
    response = HttpResponse(encoded_string, content_type='image/png')
    return response


class MofListView(ListView):
    context_object_name = 'mofs'
    model = Mof
    paginate_by = 10

    def get_queryset(self):
        return Mof.objects.order_by('name')


class MofDetailView(DetailView):
    context_object_name = 'mof_detail'
    model = Mof
    template_name = 'mof_network/mof_detail.html'


# create, read, update, and delete (CRUD)
class MofCreateView(CreateView):
    # login_url = '/login/'
    # redirect_field_name = 'mof_network/mof_list.html'
    form_class = MofForm
    model = Mof
    success_url = reverse_lazy('mof:mof_list')


class MofUpdateView(UpdateView):
    # login_url = '/login/'
    # redirect_field_name = 'mof_network/mof_detail.html'
    form_class = MofForm
    model = Mof
    # success_url = reverse_lazy('mof:mof_list')

    @staticmethod
    def get_redirect_url(self, param):
        return reverse_lazy('mof:mof_detail', kwargs={'pk': Mof.pk})


class MofDeleteView(LoginRequiredMixin, DeleteView):
    login_url = '/login/'
    model = Mof
    success_url = reverse_lazy('mof:mof_list')


class DraftListView(LoginRequiredMixin, ListView):
    login_url = '/login/'
    redirect_field_name = 'mof_network/post_draft_list.html'
    model = Post

    def get_queryset(self):
        return Post.objects.filter(date_publish__isnull=True).order_by('date_create')


def add_comment_to_mof(request, pk):
    mof = get_object_or_404(Mof, pk=pk)

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.mof = mof
            comment.save()
            return redirect('mof:mof_detail', pk=mof.pk)

        else:
            form = CommentForm()

        return render(request, 'mof_network/comment_form.html', {'form': form})
    else:
        return render(request, 'mof_network/comment_form.html')


@login_required
def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect('mof:post_list')


@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('mof:post_detail_view', pk=Comment.post.pk)


@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post_pk = Comment.post.pk
    comment.delete()
    return redirect('mof:post_detail_view', pk=post_pk)


def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('mof:index'))
                # Redirect to a success page.

            else:
                return HttpResponse('Your account is not active!')

        else:
            return HttpResponse("Invalid login credentials!")

    else:
        return render(request, 'login/login.html', {})
        # Return an 'invalid login' error message.


@login_required
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('mof:index'))
    # Redirect to a success page.

templates/mof_network/about.html
<!DOCTYPE html>
{% extends "mof_network/base.html" %}
{% block body_block%}
<div class="jumbotron">
    <h2 class="display-4">Materials Data Engineering Laboratory</h2>
    <h4>A web portal for knowledge discovery in database associated with a broad range technological and social issues that are influenced by materials science</h4>
    <button type="button" class="btn btn-primary btn-lg "><a class="link-CoRE" href="https://corebuffalo.aws.hubzero.org/">MaDE@UB</a></button>
    <button type="button" class="btn btn-secondary btn-lg"><a class="link-CoRE" href="https://corebuffalo.aws.hubzero.org/materials-informatics-toolkit/data-connectivity-module">Data Connectivity Module</a></button>
    <p class="lead"></p>
    <hr class="my-4">
    <h4>Transforming Databases from Library to Serve as a Value-added Materials Data Laboratory</h4>
    <p>MaDE@UB is a synergistic data platform for <strong>k</strong>nowledge <strong>d</strong>iscovery in <strong>d</strong>atabases (KDD), applicable to a diverse genre of data associated with technological and social issues in material science.</p>
    <p>This cyber-infrastructure provides access to a series of <strong>d</strong>ata <strong>i</strong>nfrastructure <strong>b</strong>uilding <strong>b</strong>locks (DIBBs) which include a toolkit built on materials informatics methods, a bibliography of provenance data, and which welcomes contributions of data and tools to apply KDD methods to increase the dimensionality of information.  MaDE@UB enhances the functionalities of databases from one of search and retrieval to instead achieve Knowledge Discovery across a variety of material platforms (ie. from data library to data laboratory), and aims to converge disciplines ranging from physical sciences, life sciences and social sciences.</p>
</div>
{% endblock %}

templates/mof_network/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width">
    <title>UBMDI</title>

    <script src="{% static 'lib/jquery.js' %}"></script>
    <script src="{% static 'lib/popper.min.js' %}"></script>
{#    <script src="{% static 'lib/bootstrap.min.js' %}"></script>#}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/network.css' %}">
</head>
<body>
<nav class="navbar navbar-expand-lg sticky-top navbar-primary" style="background-color: #005bbb;">
    <a class="navbar-brand text-white" href="{% url 'mof:index' %}">Overview</a>
    <div class="collapse navbar-collapse" id="navbarToggler">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0 navbar-right">
            <li><a class="nav-link text-white" href="{% url 'mof:map_view' %}">Mapping</a></li>
            <li><a class="nav-link text-white" href="{% url 'mof:mof_list' %}">List View</a></li>
            {% if user.is_authenticated %}
                <li><a class="nav-link text-white" href="{% url 'mof:mof_new' %}">New Structure</a></li>
                <li><a class="nav-link text-white" href="{% url 'mof:mof_draft_list' %}">Drafts</a></li>
                <li><a class="nav-link text-white" href="#">Hi: {{ user.username }}</a></li>
                <li><a class="nav-link text-white" href="{% url 'logout' %}">Log Out</a></li>
            {% else %}
                <li><a class="nav-link text-white" href="{% url 'login' %}">Login</a></li>
            {% endif %}
        </ul>

        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>

<div class="container">
    {% block body_block %}
    {# Anything outside of this will be inherited if you use extend. #}
    {% endblock %}
</div>
</body>
</html>

templates/mof_network/comment_form.html
{% extends "mof_network/base.html" %}
{% block body_block %}
    <h1>New Comment</h1>
    <form class="post-form" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Post Comments</button>
    </form>
{% endblock %}

templates/mof_network/index.html
<!DOCTYPE html>
{% extends "mof_network/base.html" %}
{% load staticfiles %}
{% block body_block %}
<div class="jumbotron">
    <h2 class="display-4">Materials for Clean Energy</h2>
    <p class="lead"><a href="https://pubs.rsc.org/en/content/articlelanding/2018/me/c8me00014j/unauth#!divAbstract">Correlative analysis of metal organic framework structures through manifold learning of Hirshfeld surfaces</a></p>
    <hr class="my-4">
    <p>Metal organic frameworks (MOFs) are one of the most exciting advances in solid state materials science.
        They are crystalline materials assembled with metal clusters and organic linkers, which have tailorable pore sizes, pore geometries, high void fractions, and large surface areas.
        Those features enable a wide applications of MOFs in many fields, including gas storage, separation, catalysis, and carbon capture.
        Since their first discovery, thousands of MOFs have been experimentally synthesized.
        The rich and still growing database of MOFs have also raised a crucial challenge: <br><br>
        <em>how does one identify the most promising structures, among the thousands of possibilities, for a particular application?</em><br><br>
        As synthesizing and testing a large number of MOF is not feasible in practice, the high-throughput computational screening of the MOF database can help expedite the experimental efforts.
        However, typical MOF database is high-dimensional and sparse that pose the challenge of extracting the key features and trends that could guide the discovery process.
        To address this issue, we develop a library of MOF fingerprints based on their geometric and chemical bonding interactions.
        Such fingerprints are computational ready to be analyzed with various machine learning methods.
        Using MOF as the prototype class of materials to knowledge discovery data mining clean energy.
    </p>

    <div id="coverImg" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#coverImg" data-slide-to="0" class="active"></li>
            <li data-target="#coverImg" data-slide-to="1"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img class="d-block slide" src="{% static 'images/GraphicalAbstract.png' %}" alt="First slide">
                <div class="carousel-caption d-none d-md-block slide_font">
                    <h5>Graphical Abstract</h5>
                    <p>Correlative analysis of metal organic framework</p>
                </div>
            </div>
            <div class="carousel-item">
                <img class="d-block slide" src="{% static 'images/isomap_mof508.svg' %}" alt="Second slide">
                <div class="carousel-caption d-none d-md-block slide_font">
                    <h5>Key Results</h5>
                    <p>Isomap dimensional reductions on MOF fingerprints</p>
                </div>
            </div>
        </div>
        <a class="carousel-control-prev" href="#coverImg" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#coverImg" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>
{% endblock %}

templates/mof_network/mof_confirm_delete.html
<!DOCTYPE html>
{% extends "mof_network/base.html" %}
{% block body_block %}
<div class="jumbotron">
    <h2 class="display-4">Delete {{ mof.name }}?</h2>
    <hr class="my-4">
    <form method="POST">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="{% url 'mof:mof_detail' pk=mof.pk %}">Cancel</a>
    </form>
</div>
{% endblock %}

templates/mof_network/mof_detail.html
<!DOCTYPE html>
{% extends "mof_network/base.html" %}
{% load staticfiles %}
{% block body_block%}
<div class="jumbotron">
    <h2 class="display-4">Properties of MOFs</h2>
    <p class="lead"><a href="https://pubs.rsc.org/en/content/articlelanding/2018/me/c8me00014j/unauth#!divAbstract">Correlative analysis of metal organic framework structures through manifold learning of Hirshfeld surfaces</a></p>
    <hr class="my-4">

    <div class="card-deck">
        <div class="card mb-3" style="align-content: center;">
            <img class="card-img-top" src="{{ mof_detail.fingerprint.url }}" alt="Card image cap">
        </div>

        <div class="card border-dark mb-3" style="align-content: center;">
            <div class="card text-center">
                <div class="card-body">
                    <h2 class="card-title">{{ mof_detail.name }}</h2>
                    <p class="card-text"></p>
                </div>
            </div>
            <div class="card text-right">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">Largest Cavity Diameter: {{ mof_detail.lcd }} <span>&#8491;</span></li>
                    <li class="list-group-item">Pore-limiting Diameter: {{ mof_detail.pld }} <span>&#8491;</span></li>
                    <li class="list-group-item">Accessible Surface Area: {{ mof_detail.area }} m<sup>2</sup>/g</li>
                    <li class="list-group-item">Density: {{ mof_detail.density }} g/m<sup>3</sup></li>
                    <li class="list-group-item">Formula: {{ mof_detail.formula }}</li>
                    <li class="list-group-item">Space Group: {{ mof_detail.space_group }}</li>
                    <li class="list-group-item">Volume Fraction: {{ mof_detail.vol_frac }}</li>
                </ul>

                <div class="card-body">
                    <p>Correlated with: </p>
                    {% for item in mof_detail.B.all%}
                        <a href="{% url 'mof:mof_detail' pk=item.source_id|safe %}" class="card-link">{{ item.source_id|safe }}</a>
                    {% empty %}<p>None in this dataset</p>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <a class="btn btn-primary" href="{% url 'mof:mof_update' pk=mof_detail.pk %}">Update</a>
    {% if user.is_authenticated %}
        <a class="btn btn-light" href="{% url 'mof:mof_approve' pk=mof_detail.pk %}">Approve</a>
        <a class="btn btn-warning" href="{% url 'mof:mof_delete' pk=mof_detail.pk %}">Remove</a>
    {% endif %}

    <a class="btn btn-light" href="{% url 'mof:add_comment_to_mof' pk=mof_detail.pk %}">Add Comments</a>
    {% for comment in mof_detail.comments.all %}
        <p>{{ comment.text|safe|linebreaks }} <b>Posted By:</b> {{ comment.author }}</p>
    {% empty %}<p>No Comments</p>
    {% endfor %}
</div>
{% endblock %}

templates/mof_network/mof_form.html
{% extends "mof_network/base.html" %}
{% block body_block %}
    <h1>{% if not form.instance.pk %}
            Enter New MOF structure
        {% else %}
            Update existing MOF entry
        {% endif %}
    </h1>
    <form enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary" name="button">Save</button>
    </form>
{% endblock %}

templates/mof_network/mof_list.html
<!DOCTYPE html>
{% extends "mof_network/base.html" %}
{% block body_block%}
<div class="jumbotron">
    <h2 class="display-4">List of Documented MOFs</h2>
    <p class="lead"><a href="https://pubs.rsc.org/en/content/articlelanding/2018/me/c8me00014j/unauth#!divAbstract">Correlative analysis of metal organic framework structures through manifold learning of Hirshfeld surfaces</a></p>
    <hr class="my-4">
    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Accessible Surface Area (m<sup>2</sup>/g)</th>
            <th scope="col">Formula</th>
            <th scope="col">Space Group</th>
            <th scope="col">Comments</th>
        </tr>
        </thead>
        {% for mof in mofs %}
            <tr>
                <th scope="row"><a href="{% url 'mof:mof_detail' pk=mof.pk %}">{{ mof.name }}</a></th>
                <td>{{ mof.area }}</td>
                <td>{{ mof.formula }}</td>
                <td>{{ mof.space_group }}</td>
                <td>
                    {% if mof.comments.count != 0 %}
                        <a href="{% url 'mof:mof_detail' pk=mof.pk %}">Comments: {{ mof.comments.count }}</a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
    </table>

    <div class="row">
        {% if is_paginated %}
            <div class="col-sm-4 text-left">
                Mof {{ page_obj.start_index }}-{{ page_obj.end_index }}
            </div>

            <div class="col-sm-4 text-center">
                {% if page_obj.has_previous %}
                    <span><a href="?page={{ page_obj.previous_page_number }}">Previous</a></span>
                {% endif %}
                <span>&nbsp;&nbsp;Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}&nbsp;&nbsp;</span>
                {% if page_obj.has_next %}
                    <span><a href="?page={{ page_obj.next_page_number }}">Next</a></span>
                {% endif %}
            </div>

            <div class="col-sm-4 text-right">
                <form>
                    Goto Page:<input type="text" name="page" style="width: 25px;">
                </form>
            </div>
        {% else %}
            <h3>Pagination Fails</h3>
            <p>Under Construction</p>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/mof_network/post_confirm_delete.html
{% extends "mof_network/base.html" %}
{% block body_block %}
    <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete {{ object }}</p>
        <input type="submit" class="btn btn-danger" value="Confirm">
    </form>
{% endblock %}

templates/mof_network/post_detail.html
{% extends "mof_network/base.html" %}
{% block body_block %}
<h1>{{ apatite.title }}</h1>
    {% if apatite.date_publish %}
        <div>{{ apatite.date_publish }}</div>
    {% else %}
        <a class="btn btn-info" href="{% url 'mof:post_publish' pk=apatite.pk %}">Publish</a>
    {% endif %}

    <p>{{ apatite.text|safe|linebreaksbr }}</p>

    {% if user.is_authenticated %}
        <a class="btn btn-primary" href="{% url 'mof:post_edit' pk=apatite.pk %}">Edit</a>
        <a class="btn btn-primary" href="{% url 'mof:post_remove' pk=apatite.pk %}">Cancel</a>
    {% endif %}

    <hr>

    <a class="btn btn-block" href="{% url 'mof:add_comment_to_post' pk=apatite.pk %}">Add comment</a>
    <div class="container">
        {% for comment in apatite.comments.all %}
            <br>
            {% if user.is_authenticated or comment.approved %}
                {{ comment.create_date }}
                {% if not comment.approved %}
                    <a class="btn btn-primary" href="{% url 'mof:comment_approve' pk=comment.pk %}">OK</a>
                    <a class="btn btn-primary" href="{% url 'mof:comment_remove' pk=comment.pk %}">Remove</a>
                {% endif %}
                <p>{{ comment.text|safe|linebreaks }}</p>
                <p>Post By: {{ comment.author }}</p>
            {% endif %}
            {% empty %}
            <p>No Comments!</p>
        {% endfor %}
    </div>

{% endblock %}

templates/mof_network/post_draft_list.html
{% extends "mof_network/base.html" %}
{% block body_block %}
    <div class="jumbotron">
        <p class="date">created: {{ apatite.date_create|date:"d-m-Y" }}</p>
        <h1><a href="{% url 'mof:post_detail_view' pk=apatite.pk %}">{{ apatite.title }}</a></h1>
        <p>{{ apatite.text|truncatechars:200 }}</p>
    </div>
{% endblock %}

templates/mof_network/post_form.html
{% extends "mof_network/base.html" %}
{% block body_block %}
    <h1>New Structure</h1>
    <form class="post-form" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-default" name="button">Save</button>
    </form>
{% endblock %}

templates/mof_network/post_list.html
<!DOCTYPE html>
{% extends "mof_network/base.html" %}
{% block body_block%}
<div class="jumbotron">
    <h2 class="display-4">List View</h2>
    <p class="lead"><a href="https://pubs.rsc.org/en/content/articlelanding/2018/me/c8me00014j/unauth#!divAbstract">Correlative analysis of metal organic framework structures through manifold learning of Hirshfeld surfaces</a></p>
    <hr class="my-4">
    <p>Post View</p>
    {% for apatite in apatite_list %}
        <div class="post">
        <h1><a href="{% url 'mof:post_detail_view' pk=apatite.pk %}">{{ apatite.title }}</a></h1>
        <div class="date">
            <p>Published on: {{ apatite.publish|date:"D M Y" }}</p><!--No Blank Space-->
        </div>
        <a href="{% url 'mof:post_detail_view' pk=apatite.pk %}">Comments: {{ apatite.approve_comments.count }}</a>
        </div>
    {% endfor %}
</div>
{% endblock %}